export const TAX_YEAR=2025;
export const categories={donation:{label:'บริจาคทั่วไป',icon:'Heart',color:'violet',condition:'ผู้รับต้องเป็นหน่วยรับบริจาคที่มีสิทธิ หลักฐานต้องตรงกับผู้ใช้สิทธิ หักตามจริงไม่เกิน 10% ของฐานหลังหักค่าใช้จ่ายและค่าลดหย่อน'},special:{label:'บริจาคสิทธิพิเศษ',icon:'GraduationCap',color:'violet',condition:'อาจได้สิทธิ 2 เท่าเมื่อเข้าเงื่อนไขเฉพาะ ต้องตรวจประเภทหน่วยรับ ช่วงเวลา และ e-Donation ระบบยังไม่นำมาคำนวณ'},health:{label:'ประกันสุขภาพ',icon:'ShieldCheck',color:'blue',condition:'ประกันสุขภาพตนเองตามเงื่อนไข หักไม่เกิน 25,000 บาท รวมประกันชีวิตไม่เกิน 100,000 บาท และแจ้งบริษัทส่งข้อมูล'},life:{label:'ประกันชีวิต',icon:'ShieldCheck',color:'blue',condition:'ประกันชีวิตตนเองอายุกรมธรรม์อย่างน้อย 10 ปี และเงื่อนไขอื่นตามกฎหมาย รวมประกันสุขภาพไม่เกิน 100,000 บาท'},mortgage:{label:'ดอกเบี้ยบ้าน',icon:'House',color:'orange',condition:'เฉพาะดอกเบี้ยกู้ซื้อ/สร้างที่อยู่อาศัยที่เข้าเกณฑ์ ไม่ใช่เงินต้น ไม่เกิน 100,000 บาท กู้ร่วมต้องแบ่งสิทธิ'},shopping:{label:'ซื้อสินค้า / บริการ',icon:'ShoppingBag',color:'orange',condition:'บิลทั่วไปไม่ลดหย่อนอัตโนมัติ มาตรการเฉพาะปีต้องตรวจวันซื้อ ประเภทร้าน สินค้า และ e-Tax Invoice แยกต่างหาก'},food:{label:'อาหารและเครื่องดื่ม',icon:'Coffee',color:'pink',condition:'ค่าใช้จ่ายส่วนตัวทั่วไปไม่นำมาลดหย่อนในเครื่องคำนวณนี้'},travel:{label:'เดินทาง',icon:'Car',color:'blue',condition:'ค่าใช้จ่ายส่วนตัวทั่วไปไม่นำมาลดหย่อนในเครื่องคำนวณนี้'},other:{label:'ค่าใช้จ่ายอื่น',icon:'Receipt',color:'gray',condition:'ยังระบุสิทธิไม่ได้ เก็บเอกสารและตรวจเงื่อนไขก่อนใช้สิทธิ'}};
export const sources=[{id:'rd-ins91-2568',title:'คู่มือ ภ.ง.ด.91 ปีภาษี 2568 (กรมสรรพากร)',url:'https://www.rd.go.th/fileadmin/tax_pdf/pit/2568/Ins91_241268.pdf'},{id:'rd-form91-2568',title:'แบบ ภ.ง.ด.91 ปีภาษี 2568',url:'https://www.rd.go.th/fileadmin/tax_pdf/pit/2568/241268PIT91.pdf'},{id:'rd-rates',title:'อัตราภาษีเงินได้บุคคลธรรมดา',url:'https://www.rd.go.th/59670.html'},{id:'rd-filing',title:'ยื่นภาษีออนไลน์ — กรมสรรพากร',url:'https://efiling.rd.go.th/rd-cms/'}];
export const ruleset={id:'TH-PIT-2568-SALARY-v2',taxYear:2025,buddhistYear:2568,verifiedOn:'2026-10-09',authority:'กรมสรรพากร',sourceId:'rd-ins91-2568',scope:'เงินได้ ม.40(1) ประเภทเดียว; สิทธิตามหมวดที่ระบบรองรับ',rules:[
{id:'expense',rate:.5,cap:100000,page:1,label:'ค่าใช้จ่ายเงินเดือน'},
{id:'personal',amount:60000,page:4,label:'ลดหย่อนผู้มีเงินได้'},
{id:'life',cap:100000,page:6,label:'ประกันชีวิตตามเงื่อนไข'},
{id:'health',cap:25000,combinedCap:100000,page:7,label:'ประกันสุขภาพตนเองรวมชีวิต'},
{id:'mortgage',cap:100000,page:8,label:'ดอกเบี้ยกู้ที่อยู่อาศัยตามสิทธิ'},
{id:'donation',rate:.1,page:2,label:'บริจาคทั่วไปหลังหักค่าใช้จ่ายและค่าลดหย่อน'},
{id:'progressive',limits:[150000,300000,500000,750000,1000000,2000000,5000000,null],rates:[0,.05,.1,.15,.2,.25,.30,.35],page:15,label:'ภาษีขั้นบันได'}
],unsupported:['เงินได้ประเภทอื่น / ต่างประเทศ / เงินออกจากงานแยกคำนวณ','ค่าลดหย่อนครอบครัว ประกันสังคม กองทุน และเงินได้ยกเว้น','บริจาคสิทธิพิเศษ 2 เท่าและมาตรการช้อปเฉพาะปี']};
export const defaultProfile={salary:0,bonus:0,withheld:0,scopeConfirmed:false};
export function classify(text='') {if(/บริจาค|donat|มูลนิธิ/i.test(text))return /โรงเรียน|การศึกษา|โรงพยาบาลรัฐ/.test(text)?'special':'donation';if(/ประกันสุขภาพ|health insurance/i.test(text))return 'health';if(/ประกันชีวิต|life insurance/i.test(text))return 'life';if(/ดอกเบี้ย|mortgage/i.test(text))return 'mortgage';if(/กาแฟ|อาหาร|coffee|cafe|restaurant/i.test(text))return 'food';if(/น้ำมัน|เดินทาง|taxi|grab|fuel/i.test(text))return 'travel';if(/สินค้า|ห้าง|store|shop|mart/i.test(text))return 'shopping';return 'other';}
export function eligibility(r){if(!['donation','health','life','mortgage'].includes(r.category))return ['food','travel'].includes(r.category)?'no':'review';return r.verified?'eligible':'review';}
const cents=n=>Math.round(Number(n||0)*100),baht=n=>n/100;
export function progressive(net){const rule=ruleset.rules.find(r=>r.id==='progressive');const limits=rule.limits.map(x=>x===null?Infinity:x),rates=rule.rates;let lower=0,total=0;const brackets=limits.map((upper,i)=>{const taxable=Math.max(0,Math.min(cents(net),upper===Infinity?Infinity:cents(upper))-cents(lower)),tax=taxable*rates[i],b={lower,upper,rate:rates[i],taxable:baht(taxable),tax:baht(Math.round(tax))};total+=tax;lower=upper;return b;});return {tax:baht(Math.round(total)),brackets};}
export function calculate(profile=defaultProfile,receipts=[],year=TAX_YEAR){
 if(year!==TAX_YEAR)throw Error('รองรับเฉพาะกฎปีภาษี 2568 ไม่ใช้กฎข้ามปี');
 const rule=id=>ruleset.rules.find(r=>r.id===id),incomeC=cents(profile.salary)+cents(profile.bonus),withheldC=cents(profile.withheld);
 const expenseC=Math.min(Math.round(incomeC*rule('expense').rate),cents(rule('expense').cap)),personalC=cents(rule('personal').amount);
 const rows=receipts.filter(r=>r.date.startsWith(`${year}-`)&&eligibility(r)==='eligible'),sum=cat=>rows.filter(r=>r.category===cat).reduce((s,r)=>s+cents(r.amount),0);
 const lifeC=Math.min(sum('life'),cents(rule('life').cap)),healthC=Math.min(sum('health'),cents(rule('health').cap),cents(rule('health').combinedCap)-lifeC),mortgageC=Math.min(sum('mortgage'),cents(rule('mortgage').cap));
 const beforeDonationC=Math.max(0,incomeC-expenseC-personalC-lifeC-healthC-mortgageC);
 // Floor the ceiling to satang so a claim never exceeds 10% due to rounding.
 const donationC=Math.min(sum('donation'),Math.floor(beforeDonationC*rule('donation').rate)),deductionsC=personalC+lifeC+healthC+mortgageC+donationC,netC=Math.max(0,incomeC-expenseC-deductionsC),result=progressive(baht(netC)),baseline=progressive(baht(Math.max(0,incomeC-expenseC-personalC))).tax;
 const warnings=[];if(!profile.scopeConfirmed)warnings.push('ยังไม่ยืนยันว่ารายได้และสิทธิทั้งหมดอยู่ในขอบเขตที่ระบบรองรับ');if(receipts.some(r=>eligibility(r)==='review'))warnings.push('มีรายการรอตรวจสอบที่ยังไม่นับเป็นค่าลดหย่อน');
 return {income:baht(incomeC),expense:baht(expenseC),personal:baht(personalC),life:baht(lifeC),health:baht(healthC),mortgage:baht(mortgageC),donation:baht(donationC),donationBase:baht(beforeDonationC),deductions:baht(deductionsC),net:baht(netC),...result,withheld:baht(withheldC),balance:baht(cents(result.tax)-withheldC),saved:baht(cents(baseline)-cents(result.tax)),eligible:rows.length,rulesetId:ruleset.id,source:sources[0].url,coverageStatus:warnings.length?'incomplete':'within-supported-scope',warnings};
}
export function validateProfile(p){const out={scopeConfirmed:p.scopeConfirmed===true};for(const k of ['salary','bonus','withheld']){const n=Number(p[k]);if(!Number.isFinite(n)||n<0||n>1e10)throw Error('รายได้และภาษีต้องเป็นตัวเลขตั้งแต่ 0 ถึง 10,000,000,000');out[k]=baht(cents(n));}return out;}
export function validateReceipt(r){const merchant=String(r.merchant||'').trim();if(!merchant||merchant.length>160)throw Error('กรุณาระบุชื่อร้านหรือหน่วยรับ ไม่เกิน 160 ตัวอักษร');const amount=Number(r.amount);if(!Number.isFinite(amount)||amount<=0||amount>1e9)throw Error('ยอดเงินต้องมากกว่า 0 และไม่เกิน 1,000,000,000');const date=String(r.date||'');if(!/^2025-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date)throw Error('กรุณาระบุวันที่จริงในปีภาษี 2568 (2025)');if(!Object.hasOwn(categories,r.category))throw Error('ประเภทไม่ถูกต้อง');const image=String(r.image||'');if(image&&(!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(image)||image.length>5600000))throw Error('รูปต้องเป็น JPG, PNG หรือ WebP ขนาดไม่เกิน 4 MB');return {merchant,amount:Math.round(amount*100)/100,date,category:r.category,verified:r.verified===true,notes:String(r.notes||'').slice(0,2000),ocrText:String(r.ocrText||'').slice(0,12000),image};}
export function parseOCR(text){const category=classify(text);const lines=text.split('\n').map(x=>x.trim()).filter(Boolean);const totalLines=lines.filter(x=>/ยอดสุทธิ|ยอดรวม|รวมทั้งสิ้น|grand total|total|จำนวนเงิน/i.test(x));let amount='';for(const line of totalLines.reverse()){const matches=line.match(/\d[\d,]*\.\d{2}/g);if(matches?.length){amount=Number(matches.at(-1).replaceAll(',',''));break;}}let date='';const m=text.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(m){const y=Number(m[3])>2400?Number(m[3])-543:Number(m[3]);date=`${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;}return {merchant:lines[0]?.slice(0,160)||'',amount,date,category,ocrText:text};}
export function makeSeed(){return {profile:{salary:600000,bonus:50000,withheld:25000},receipts:[{merchant:'มูลนิธิเพื่อการศึกษา',amount:2500,date:'2025-09-16',category:'special',verified:false},{merchant:'ประกันสุขภาพประจำปี',amount:18000,date:'2025-09-12',category:'health',verified:true},{merchant:'Everyday Coffee',amount:185,date:'2025-09-10',category:'food',verified:false},{merchant:'มูลนิธิสาธารณกุศล (ตัวอย่าง)',amount:1500,date:'2025-09-08',category:'donation',verified:true},{merchant:'หนังสือและอุปกรณ์ทำงาน',amount:2490,date:'2025-09-04',category:'shopping',verified:false},{merchant:'ประกันชีวิตประจำปี',amount:24000,date:'2025-08-28',category:'life',verified:true}].map((r,i)=>({...r,id:`seed-${i}`,notes:'ข้อมูลสมมติสำหรับทดลองใช้งาน',image:'',ocrText:''}))};}
