import {randomBytes,scrypt as scryptCb,timingSafeEqual,createHash,randomUUID} from 'node:crypto';
import {promisify} from 'node:util';
import {defaultProfile,makeSeed} from '../shared/tax.mjs';
import {httpError,publicUser,passwordValue} from './db.mjs';
const scrypt=promisify(scryptCb);
export const hash=async(p,s)=>(await scrypt(p,s,64)).toString('hex');
export const digest=s=>createHash('sha256').update(s).digest('hex');
export async function addUser(db,a,password,role='user',seed=false){passwordValue(password);const id=randomUUID(),salt=randomBytes(16).toString('hex'),encoded=await hash(password,salt),data=seed?makeSeed():{profile:defaultProfile,receipts:[]};db.exec('BEGIN IMMEDIATE');try{db.prepare('INSERT INTO users(id,name,email,username,role,status,salt,password,profile,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,a.name,a.email,a.username,role,'active',salt,encoded,JSON.stringify(data.profile),Date.now());for(const r of data.receipts)db.prepare('INSERT INTO receipts(id,user_id,data) VALUES(?,?,?)').run(randomUUID(),id,JSON.stringify(r));db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');if(String(e.message).includes('UNIQUE'))throw httpError(409,'อีเมลหรือ username นี้ถูกใช้แล้ว');throw e;}return db.prepare('SELECT * FROM users WHERE id=?').get(id);}
export async function verify(u,password){const p=typeof password==='string'&&password.length<=128?password:'';const actual=await hash(p,u?.salt||'taxmate-dummy-salt');return !!u&&timingSafeEqual(Buffer.from(u.password,'hex'),Buffer.from(actual,'hex'));}
export function authTools(db){const tokenOf=req=>(req.get('cookie')||'').match(/(?:^|;\s*)taxmate_session=([a-f0-9]{64})(?:;|$)/)?.[1];const cookie=(res,value,age)=>res.setHeader('Set-Cookie',`taxmate_session=${value}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${age}`);return {tokenOf,clear:res=>cookie(res,'',0),session(u,res){const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(digest(token),u.id,Date.now()+86400000);cookie(res,token,86400);return res.json(publicUser(u));},auth(req,res,next){const token=tokenOf(req),u=token&&db.prepare("SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token=? AND s.expires>? AND u.status='active'").get(digest(token),Date.now());if(!u)return next(httpError(401,'กรุณาเข้าสู่ระบบอีกครั้ง'));req.user=u;next();}};}
export const roleGuard=(...roles)=>(req,res,next)=>roles.includes(req.user.role)?next():next(httpError(403,'บัญชีนี้ไม่มีสิทธิ์ทำรายการนี้'));
