import express from 'express';
import {DatabaseSync} from 'node:sqlite';
import {randomBytes,scryptSync,timingSafeEqual,createHash,randomUUID} from 'node:crypto';
import {mkdirSync,existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {makeSeed,defaultProfile,validateProfile,validateReceipt,calculate} from '../shared/tax.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),dbPath=process.env.TAXMATE_DB||path.join(root,'backend/data/taxmate.sqlite');mkdirSync(path.dirname(dbPath),{recursive:true});
const db=new DatabaseSync(dbPath);db.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;');db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,salt TEXT NOT NULL,password TEXT NOT NULL,profile TEXT NOT NULL);CREATE TABLE IF NOT EXISTS receipts(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,data TEXT NOT NULL);CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires INTEGER NOT NULL);`);
const hash=(p,s)=>scryptSync(p,s,64).toString('hex'),digest=s=>createHash('sha256').update(s).digest('hex');
function addUser(name,email,password,seed=false){const id=randomUUID(),salt=randomBytes(16).toString('hex'),data=seed?makeSeed():{profile:defaultProfile,receipts:[]};db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?)').run(id,name,email,salt,hash(password,salt),JSON.stringify(data.profile));for(const r of data.receipts)db.prepare('INSERT INTO receipts VALUES(?,?,?)').run(randomUUID(),id,JSON.stringify(r));return db.prepare('SELECT * FROM users WHERE id=?').get(id);}
if(!db.prepare('SELECT id FROM users WHERE email=?').get('demo@taxmate.local'))addUser('คุณเพื่อน','demo@taxmate.local',randomBytes(32).toString('hex'),true);
const app=express();app.disable('x-powered-by');app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Frame-Options','DENY');if(req.path.startsWith('/api'))res.setHeader('Cache-Control','no-store');if(['POST','PUT','DELETE'].includes(req.method)){const origin=req.get('origin');if(origin&&origin!==`http://${req.get('host')}`&&origin!==`https://${req.get('host')}`)return res.status(403).json({error:'Origin ไม่ได้รับอนุญาต'});if(req.headers['sec-fetch-site']==='cross-site')return res.status(403).json({error:'ไม่อนุญาตคำขอข้ามเว็บไซต์'});if(!/^application\/json(?:;|$)/i.test(req.get('content-type')||''))return res.status(415).json({error:'ต้องส่ง JSON'});}next();});app.use(express.json({limit:'35mb'}));
const attempts=new Map();app.use('/api/auth',(req,res,next)=>{if(req.method!=='POST')return next();const key=req.ip,now=Date.now();let a=attempts.get(key);if(!a||a.until<now){a={n:0,until:now+60000};attempts.set(key,a);}if(++a.n>30)return res.status(429).json({error:'ลองหลายครั้งเกินไป กรุณารอ 1 นาที'});next();});setInterval(()=>{for(const [k,v] of attempts)if(v.until<Date.now())attempts.delete(k);db.prepare('DELETE FROM sessions WHERE expires < ?').run(Date.now());},60000).unref();
const publicUser=u=>({id:u.id,name:u.name,email:u.email,demo:u.email==='demo@taxmate.local'});
function startSession(u,res){const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(digest(token),u.id,Date.now()+86400000);res.setHeader('Set-Cookie',`taxmate_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400`);return res.json(publicUser(u));}
function sessionToken(req){return (req.get('cookie')||'').match(/(?:^|;\s*)taxmate_session=([a-f0-9]{64})(?:;|$)/)?.[1];}
function auth(req,res,next){const token=sessionToken(req);const u=token&&db.prepare('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token=? AND s.expires>?').get(digest(token),Date.now());if(!u)return res.status(401).json({error:'กรุณาเข้าสู่ระบบ'});req.user=u;next();}
function dataFor(id){const u=db.prepare('SELECT profile FROM users WHERE id=?').get(id);return {profile:JSON.parse(u.profile),receipts:db.prepare('SELECT id,data FROM receipts WHERE user_id=? ORDER BY rowid DESC').all(id).map(r=>({...JSON.parse(r.data),id:r.id}))};}
app.get('/api/health',(req,res)=>res.json({app:'taxmate',status:'ok',storage:'sqlite'}));
app.post('/api/auth/register',(req,res)=>{const {name,password}=req.body,email=String(req.body.email||'').trim().toLowerCase();if(typeof name!=='string'||!name.trim()||name.length>80||!/^\S+@\S+\.\S+$/.test(email)||email.length>200||typeof password!=='string'||password.length<8||password.length>128)return res.status(400).json({error:'ชื่อ อีเมล หรือรหัสผ่านไม่ถูกต้อง (รหัสผ่าน 8–128 ตัวอักษร)'});if(db.prepare('SELECT id FROM users WHERE email=?').get(email))return res.status(409).json({error:'อีเมลนี้มีบัญชีแล้ว'});startSession(addUser(name.trim(),email,password),res);});
app.post('/api/auth/login',(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=req.body.password;if(typeof password!=='string'||password.length>128)return res.status(400).json({error:'ข้อมูลไม่ถูกต้อง'});const u=db.prepare('SELECT * FROM users WHERE email=?').get(email),actual=hash(password,u?.salt||'dummy-salt');if(!u||!timingSafeEqual(Buffer.from(u.password,'hex'),Buffer.from(actual,'hex')))return res.status(401).json({error:'อีเมลหรือรหัสผ่านไม่ถูกต้อง'});startSession(u,res);});
app.post('/api/auth/demo',(req,res)=>startSession(db.prepare('SELECT * FROM users WHERE email=?').get('demo@taxmate.local'),res));
app.get('/api/auth/me',auth,(req,res)=>res.json(publicUser(req.user)));
app.post('/api/auth/logout',(req,res)=>{const token=sessionToken(req);if(token)db.prepare('DELETE FROM sessions WHERE token=?').run(digest(token));res.setHeader('Set-Cookie','taxmate_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');res.json({ok:true});});
app.use('/api',auth);app.get('/api/data',(req,res)=>res.json(dataFor(req.user.id)));app.get('/api/summary',(req,res)=>{const d=dataFor(req.user.id);res.json(calculate(d.profile,d.receipts));});
app.put('/api/profile',(req,res)=>{const p=validateProfile(req.body);db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(p),req.user.id);res.json(p);});
app.post('/api/receipts',(req,res)=>{const receipt=validateReceipt(req.body),id=randomUUID();db.prepare('INSERT INTO receipts VALUES(?,?,?)').run(id,req.user.id,JSON.stringify(receipt));res.status(201).json({...receipt,id});});
app.put('/api/receipts/:id',(req,res)=>{const r=validateReceipt(req.body),result=db.prepare('UPDATE receipts SET data=? WHERE id=? AND user_id=?').run(JSON.stringify(r),req.params.id,req.user.id);if(!result.changes)return res.status(404).json({error:'ไม่พบบิล'});res.json({...r,id:req.params.id});});
app.delete('/api/receipts/:id',(req,res)=>{const r=db.prepare('DELETE FROM receipts WHERE id=? AND user_id=?').run(req.params.id,req.user.id);if(!r.changes)return res.status(404).json({error:'ไม่พบบิล'});res.json({ok:true});});
app.post('/api/import',(req,res)=>{if(!Array.isArray(req.body.receipts)||req.body.receipts.length>1000)throw Error('จำนวนรายการไม่ถูกต้อง');const p=validateProfile(req.body.profile),rows=req.body.receipts.map(validateReceipt);db.exec('BEGIN');try{db.prepare('DELETE FROM receipts WHERE user_id=?').run(req.user.id);db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(p),req.user.id);for(const r of rows)db.prepare('INSERT INTO receipts VALUES(?,?,?)').run(randomUUID(),req.user.id,JSON.stringify(r));db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}res.json({ok:true});});
app.delete('/api/data',(req,res)=>{db.exec('BEGIN');try{db.prepare('DELETE FROM receipts WHERE user_id=?').run(req.user.id);db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(defaultProfile),req.user.id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}res.json({ok:true});});
app.use('/api',(req,res)=>res.status(404).json({error:'ไม่พบ endpoint'}));const dist=path.join(root,'dist');if(existsSync(dist))app.use(express.static(dist));app.get('/',(req,res)=>res.status(503).send('Build frontend first: npm run build'));
app.use((err,req,res,next)=>{if(err.type==='entity.too.large')return res.status(413).json({error:'ข้อมูลใหญ่เกิน 35 MB'});if(err instanceof SyntaxError)return res.status(400).json({error:'JSON ไม่ถูกต้อง'});if(err.code?.startsWith('ERR_SQLITE')){console.error(err.code);return res.status(500).json({error:'ฐานข้อมูลไม่พร้อม กรุณาลองอีกครั้ง'});}res.status(400).json({error:err.message||'ข้อมูลไม่ถูกต้อง'});});
const port=Number(process.env.PORT)||3000;const server=app.listen(port,'127.0.0.1',()=>console.log(`Taxmate ready: http://localhost:${port}\nDatabase: ${dbPath}\nPress Ctrl+C to stop.`));function stop(){server.close(()=>{db.close();process.exit(0);});}process.on('SIGTERM',stop);process.on('SIGINT',stop);
