import {DatabaseSync} from 'node:sqlite';import {performance} from 'node:perf_hooks';import {mkdirSync,writeFileSync,statSync} from 'node:fs';import path from 'node:path';import os from 'node:os';
// Separate synthetic database. Never open the live application DB.
const rows=Number((process.argv[2]||'300000').replace(/^--rows=/,''));if(!Number.isInteger(rows)||rows<10000||rows>2000000)throw Error('Rows must be 10000..2000000');
mkdirSync('lab-output',{recursive:true});mkdirSync('manual',{recursive:true});const file=path.resolve('lab-output',`indexing-${Date.now()}.sqlite`),db=new DatabaseSync(file);db.exec('PRAGMA journal_mode=DELETE; CREATE TABLE receipts(id INTEGER PRIMARY KEY,user_id TEXT NOT NULL,receipt_date TEXT NOT NULL,category TEXT NOT NULL,amount INTEGER NOT NULL);');
const insert=db.prepare('INSERT INTO receipts VALUES(?,?,?,?,?)');const data=i=>[i,`u${i%1000}`,`2025-${String(1+(Math.floor(i/1000)%12)).padStart(2,'0')}-${String(1+(Math.floor(i/12000)%28)).padStart(2,'0')}`,['food','donation','health','life'][i%4],100+(i*17)%50000];
let t=performance.now();db.exec('BEGIN');for(let i=1;i<=rows;i++)insert.run(...data(i));db.exec('COMMIT');const generationMs=performance.now()-t;
const sql="SELECT id,receipt_date,amount FROM receipts WHERE user_id=? AND receipt_date>=? AND receipt_date<=? ORDER BY receipt_date DESC,id LIMIT 20",args=['u42','2025-03-01','2025-12-31'];
function queryRun(){const q=db.prepare(sql);for(let i=0;i<5;i++)q.all(...args);const times=[];let values;for(let i=0;i<50;i++){const start=performance.now();values=q.all(...args);times.push(performance.now()-start);}times.sort((a,b)=>a-b);return {medianMs:(times[24]+times[25])/2,p95Ms:times[47],meanMs:times.reduce((a,b)=>a+b,0)/times.length,rowsReturned:values.length,result:values,plan:db.prepare('EXPLAIN QUERY PLAN '+sql).all(...args)};}
function writes(){db.exec('BEGIN');const start=performance.now();for(let i=rows+1;i<=rows+5000;i++)insert.run(...data(i));const ms=performance.now()-start;db.exec('ROLLBACK');return ms;}
const before=queryRun(),insertBeforeMs=writes(),sizeBeforeBytes=statSync(file).size;
t=performance.now();db.exec('CREATE INDEX idx_receipts_user_date ON receipts(user_id,receipt_date DESC,id); ANALYZE;');const indexBuildMs=performance.now()-t,after=queryRun(),insertAfterMs=writes();if(JSON.stringify(before.result)!==JSON.stringify(after.result))throw Error('Result mismatch');delete before.result;delete after.result;
const result={measuredAt:new Date().toISOString(),synthetic:true,rows,users:1000,node:process.version,sqlite:db.prepare('SELECT sqlite_version() version').get().version,cpu:os.cpus()[0].model,query:sql,parameters:args,warmups:5,repetitions:50,generationMs,indexBuildMs,before,after,speedup:before.medianMs/after.medianMs,insertBatchRows:5000,insertBeforeMs,insertAfterMs,sizeBeforeBytes,sizeAfterBytes:statSync(file).size,notes:'Measured locally on deterministic synthetic data; warmed reads, no concurrency. 5,000 write timings exclude commit and are rolled back. Results are workload/hardware-specific, not guaranteed production speed.'};db.close();writeFileSync('manual/indexing-results.json',JSON.stringify(result,null,2));writeFileSync('manual/INDEXING-RESULTS.md',`# Indexing experiment\n\nRows: ${rows.toLocaleString()} (synthetic), users: 1,000.\n\n| Metric | Before | After |\n|---|---:|---:|\n| Median query ms | ${before.medianMs.toFixed(4)} | ${after.medianMs.toFixed(4)} |\n| p95 ms | ${before.p95Ms.toFixed(4)} | ${after.p95Ms.toFixed(4)} |\n| 5,000 inserts ms, no commit | ${insertBeforeMs.toFixed(2)} | ${insertAfterMs.toFixed(2)} |\n| DB bytes | ${sizeBeforeBytes} | ${result.sizeAfterBytes} |\n\nMeasured median speedup: ${result.speedup.toFixed(1)}x.\n\nBefore: \`${before.plan.map(x=>x.detail).join('; ')}\`\n\nAfter: \`${after.plan.map(x=>x.detail).join('; ')}\`\n\n${result.notes}\n`);console.log(JSON.stringify(result,null,2));
